## Numpy array and basic 

In [2]:
import numpy as np

### creating arrays from list 

In [5]:
arr_1d = np.array([1,2,3,4,5])
print("1d array :",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array :",arr_2d)

1d array : [1 2 3 4 5]
2d array : [[1 2 3]
 [4 5 6]]


In [11]:
py_list = [1,2,3,4]
print("python list multiplication",py_list * 2)

py_array = np.array([1,2,3,4])
print("python arrray multiplication",py_array * 2)

python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python arrray multiplication [2 4 6 8]


In [39]:
import time
start = time.time()#use for current time laps(not human readable)

print(time.ctime())#use for current human readable time 

Tue Jun 24 16:57:56 2025


## It measures how long it takes to:

Create a list of 100,000 numbers, where each number is multiplied by 2

In [40]:
import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n list operation time: ", time.time()-start)


 list operation time:  0.005216836929321289


same for array 

In [41]:
start = time.time()
np_array = np.arange(10000) * 2
print("\n Numpy operation time:", time.time() - start)


 Numpy operation time: 0.0008804798126220703


creating arrays from scratch

In [60]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)

ones = np.ones((3,4))
print("ones array:\n",ones)

full = np.full((2,2), 7)
print("full array: \n",full)

#imp 
random = np.random.random((2,3))
print("random array:\n",random)


#..............(start , stop ,step)
sequence = np.arange(0 , 10 , 2)
print("sequence array: \n", sequence)


zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array:
 [[0.58760469 0.98971467 0.97760844]
 [0.67836817 0.94167901 0.59255433]]
sequence array: 
 [0 2 4 6 8]


## Vector , Matrix and Tensor

In [51]:
vector = np.array([1,2,3])
print("vector:" , vector)

#2D array are alwase called matrix
matrix= np.array([[1,2,3],[4,5,6]])
print("Matrix:",matrix)

tensor= np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("Tensor:",tensor)


vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array properties

In [59]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("shape:", arr.shape)
print("Dimensions:",arr.ndim)
print("Size:", arr.size)
print("Data type:",arr.dtype)

shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64


## Array Reshaping

In [75]:
arr =np.arange(12)
print("original array", arr)

# print("reshaped array:",arr.reshape((3,4)))

reshaped = arr.reshape((3,4))
print("\n Reshaped array ", reshaped)
#reshaping of array is have a condition that reshape array size is equal to the size of orignal array.


flattened = reshaped.flatten()
print("\n Flattend array", flattened)

raveled = reshaped.ravel()
print("\n raveled array", raveled)
# flattened & raveled is same but ravel returns view insted of copy 


#Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)


original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattend array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
