## Numpy Array operations

In [ ]:
import numpy as np

## Slicing 

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("Slicing with step", arr[2:7:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
Slicing with step [3 5 7]
Negative indexing 8


In [12]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element:", arr_2d[1,2])
print("Entire row:", arr_2d[1])
print("Entire coloum:", arr_2d[:,1])

specific element: 6
Entire row: [4 5 6]
Entire coloum: [2 5 8]


## Sorting

In [18]:
unsorted = np.array([3,1,2,5,4,6,7,9,8])
print("sorted Array:", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))

sorted Array: [1 2 3 4 5 6 7 8 9]
sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [19]:
numbers =np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


Filter with mask

In [ ]:
mask = numbers >  5
print("numbers greater than 5:",numbers[mask])

mask = numbers < 5 
print("numbers less than 5:", numbers[mask])

numbers greater than 5: [5]
numbers less than 5: [1 2 3 4]


## Fancy indexing vs np.where()

In [30]:
#put the values of index 0,2,4 of numbers array , in indices 
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers >5)
print("NP wher", numbers[where_result])

[1 3 5]
NP wher [ 6  7  8  9 10]


In [32]:

condition_array= np.where(numbers >5 , "true" ,"flase")
#( numbers array me jo number 5 se bada ho wha pe true likho , else false kardo )
print(numbers)
print(condition_array)


[ 1  2  3  4  5  6  7  8  9 10]
['flase' 'flase' 'flase' 'flase' 'flase' 'true' 'true' 'true' 'true'
 'true']


## Adding and removing Data

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
#for merging two array 
combine = np.concatenate((arr1 , arr2))
print(combine)

[1 2 3 4 5 6]


### array compatibility

In [34]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,8,9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [36]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

#vstack is used for row adding
with_new_row = np.vstack((original , new_row))
print(original)
print(with_new_row)

#hstack is used for column adding 
new_col =np.array([[7],[8]])
with_new_col = np.hstack((original , new_col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 7]
 [3 4 8]]


In [37]:
arr =np.array([1,2,3,4,5])
deleted = np.delete(arr, 3)
print(deleted)

[1 2 3 5]
